### ISSUE TITLE
core dump with fftw

### ISSUE THREAD

**Issue by psteinb** [mpicbg-scicomp/gearshifft_publication#7]
this is weird:

```
$ ./gearshifft_fftw -e 512 -o test.csv
Running 8 test cases...

*** No errors detected
Results dumped to test.csv
Segmentation fault (core dumped)
```

the backtrace indicates that the segfault was caused in the test framework, if I am not mistaken:
```
#0  0x00002aaaadb22aad in malloc_consolidate () from /lib64/libc.so.6
#1  0x00002aaaadb23f06 in _int_free () from /lib64/libc.so.6
#2  0x0000000000679660 in boost::checked_array_delete<char> (x=0x9ca7b0 "p͛")
    at /home/steinbac/software/boost/1.60.0-gcc520/include/boost/core/checked_delete.hpp:41
#3  0x000000000066bdef in boost::scoped_array<char>::~scoped_array (
    this=0x9a8ca0 <boost::unit_test::singleton<boost::unit_test::unit_test_monitor_t>::instance()::the_inst+32>, __in_chrg=<optimized out>)
    at /home/steinbac/software/boost/1.60.0-gcc520/include/boost/smart_ptr/scoped_array.hpp:69
#4  0x000000000065bd40 in boost::execution_monitor::~execution_monitor (
    this=0x9a8c80 <boost::unit_test::singleton<boost::unit_test::unit_test_monitor_t>::instance()::the_inst>, __in_chrg=<optimized out>)
    at /home/steinbac/software/boost/1.60.0-gcc520/include/boost/test/execution_monitor.hpp:288
#5  0x000000000066be0a in boost::unit_test::unit_test_monitor_t::~unit_test_monitor_t (
    this=0x9a8c80 <boost::unit_test::singleton<boost::unit_test::unit_test_monitor_t>::instance()::the_inst>, __in_chrg=<optimized out>)
    at /home/steinbac/software/boost/1.60.0-gcc520/include/boost/test/unit_test_monitor.hpp:33
#6  0x00002aaaadae01da in __cxa_finalize () from /lib64/libc.so.6
#7  0x00002aaaaad0bb13 in __do_global_dtors_aux ()
   from /home/steinbac/software/boost/1.60.0-gcc520/lib/libboost_unit_test_framework.so.1.60.0
#8  0x00007fffffffda20 in ?? ()
#9  0x00002aaaaaabaa1a in _dl_fini () from /lib64/ld-linux-x86-64.so.2
Backtrace stopped: frame did not save the PC
```

**Comment by psteinb** [comment]
wrong repo :(
